site_name: cropdusters
theme:
  name: readthedocs
  palette:
    primary: blue
    accent: light blue
    toggle:
      icon: menu
      name: Menu
nav:
  - Home: index.md
  - API Reference: extract.md
plugins:
  - mkdocstrings
