version: 2

sources:
  - name: cropdusters
    database: dev
    schema: main
    tables:
      - name: crop_weather
      - name: crop_yield
        # Define other properties and columns if necessary
      - name: crop_price
        # Define other properties and columns if necessary



models:
  - name: crop_chooser_model
    description: "Stores"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: state_alpha

  - name: crop_yield_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: crop_price_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


exposures:

  - name: crop_chooser_reccomender
    label: Crop reccomendation based on data
    type: notebook # --> Dashboard          
    maturity: medium                         
    #url : https://ADD_LOCATION_LATER
    description: >
      Gives a reccomendation of the best crop to grow in a given field based on various parameters in order to optimize output and profit

    depends_on:
      - source('cropdusters', 'crop_weather')
      - ref('crop_price_model')
      - ref('crop_yield_model')

    owner:
      name: Jack Weitzner
      email: j.p.weitzner@wustl.edu


  
  - name: crop_price_model
    maturity: high
    type: analysis
    description: >
      Pulls pricing data from the market and uses it to suggest the price of a given crop in a given year"
    
    depends_on:
      - source ('cropdusters', 'crop_price')
      
    owner:
      name: Jack Weitzner
      email: j.p.weitzner@wustl.edu



  - name: crop_yield_model
    maturity: low
    type: ml
    description: >
      Predicts the yield of a given crop in a given year based on historical data and current growing conditions"
    
    depends_on:
      - source ('cropdusters', 'crop_yield')
      - source ('cropdusters', 'crop_weather')
      
    owner:
      name: Jack Weitzner
      email: j.p.weitzner@wustl.edu